# Travis is now container based which doesn't support sudo
sudo: false
language: csharp
solution: InjectionMap.sln

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: never #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    
install:
  - nuget restore InjectionMap.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Release InjectionMap.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./src/Tests/InjectionMap.Integration.UnitTests/bin/Release/InjectionMap.Integration.UnitTests.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./src/Tests/InjectionMap.Test.Integration/bin/Release/InjectionMap.Test.Integration.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./src/Tests/InjectionMap.UnitTests/bin/Release/InjectionMap.UnitTests.dll